apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustershift-benchmark
  namespace: benchmark
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-reader
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-reader-binding
subjects:
  - kind: ServiceAccount
    name: clustershift-benchmark
    namespace: benchmark
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustershift-benchmark-deployment
  namespace: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustershift-benchmark-deployment
  template:
    metadata:
      labels:
        app: clustershift-benchmark-deployment
    spec:
      serviceAccountName: clustershift-benchmark
      containers:
        - name: clustershift-benchmark-deployment
          image: ghcr.io/romankudravcev/clustershift-benchmarker:latest
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: clustershift-benchmark-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: clustershift-benchmark-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: clustershift-benchmark-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: clustershift-benchmark-config
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: clustershift-benchmark-config
                  key: DB_NAME
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: clustershift-benchmark-config
                  key: DB_TYPE
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: clustershift-benchmark-config
                  key: MONGODB_URI
          ports:
            - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: clustershift-benchmark-service
  namespace: benchmark
spec:
  selector:
    app: clustershift-benchmark-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clustershift-benchmark-ingress-route
  namespace: benchmark
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: clustershift-benchmark-service
          port: 80
